#!/bin/bash
################################################################################
# build_header.sh
#
# This script is used for merging the files in src into a single header file.
# It takes the target filename as a parameter.
#
################################################################################

filename=$1
srcdir="src"

function clear_file {
  echo -n "" > $filename
}

function add_license {
  #use sed to prepend "// " to each line of LICENSE
  sed -e 's/^/\/\/ /' LICENSE >> $filename
}

function add_top_comment {
  echo "//==============================================================================" >> $filename
  echo "//" >> $filename
  echo "//                                cppMatrix" >> $filename
  echo "//" >> $filename
  echo "//------------------------------------------------------------------------------" >> $filename
  echo "//" >> $filename
  echo "//               THIS FILE WAS GENERATED BY MERGING MULTIPLE FILES." >> $filename
  echo "//                      PLEASE DON'T EDIT IT DIRECTLY!" >> $filename
  echo "//" >> $filename
  echo "//==============================================================================" >> $filename
  echo "//" >> $filename
  add_license
  echo "//" >> $filename
  echo "//==============================================================================" >> $filename
}

function add_top_header_guard {
  echo "#ifndef ACTINIUM_MAT_MATRIX_H" >> $filename
  echo "#define ACTINIUM_MAT_MATRIX_H" >> $filename
  echo "" >> $filename
}

function add_bottom_header_guard {
  echo "#endif" >> $filename
}

function append_file {
  echo "//==============================================================================" >> $filename
  echo "//" >> $filename
  echo -n "// Included from: " >> $filename
  echo $1 >> $filename
  echo "//" >> $filename
  echo "//==============================================================================" >> $filename
  echo "" >> $filename
  echo -n "#line 1 \"" >> $filename
  echo -n $1 >> $filename
  echo "\"" >> $filename
  cat $srcdir/$1 >> $filename
  echo "" >> $filename
}

echo "Generating Header File."

clear_file

add_top_comment
add_top_header_guard

append_file matrix.h
append_file matrix_constructors_impl.h
append_file matrix_assignment_impl.h
append_file matrix_access_impl.h
append_file matrix_math_impl.h
append_file matrix_modifiers_impl.h
append_file matrix_iterators_impl.h
append_file matrix_comparison_impl.h
append_file matrix_helper_functions_impl.h

add_bottom_header_guard
